### ISSUE TITLE
error ModuleNotFoundError: No module named 'winreg'

### ISSUE THREAD

**Issue by bobwatcherx** [yjg30737/pyqt-frameless-window#7]
i get error when install
 python3 -m pip install pyqt-frameless-window

ModuleNotFoundError: No module named 'winreg'

root@minto-Lenovo-V145-14AST:/home/minto/belajar/pysidepro/pyqt-frameless-window# python3 sample.py 
Traceback (most recent call last):
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/sample.py", line 8, in <module>
    from pyqt_frameless_window import FramelessDialog, FramelessWidget, FramelessMainWindow
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/pyqt_frameless_window/__init__.py", line 1, in <module>
    from pyqt_frameless_window.framelessWindow import FramelessWidget, FramelessDialog, FramelessMainWindow
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/pyqt_frameless_window/framelessWindow.py", line 6, in <module>
    from pyqt_frameless_window.base.baseWidget import BaseWidget
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/pyqt_frameless_window/base/baseWidget.py", line 5, in <module>
    from pyqt_frameless_window.windows import TitleBar
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/pyqt_frameless_window/windows/__init__.py", line 1, in <module>
    from pyqt_frameless_window.windows.baseWidget import BaseWidget
  File "/home/minto/belajar/pysidepro/pyqt-frameless-window/pyqt_frameless_window/windows/baseWidget.py", line 2, in <module>
    from winreg import ConnectRegistry, HKEY_CURRENT_USER, OpenKey, KEY_READ, QueryValueEx
ModuleNotFoundError: No module named 'winreg'

**Comment by yjg30737** [comment]
You have to install legacy version(0.0.61) if your OS is not Windows.

`python3 -m pip install pyqt-frameless-window==0.0.61`

The current version(v0.0.82) only works in Windows, sorry to say.

winreg is the library for Windows, so it can't be installed.

Someday i will make this work in Linux, but not now.
